//go:build darwin

package tunnel

import (
	"fmt"
	"strings"
)

// darwinConfigurator drives route(8) and networksetup(8). It requires root.
//
// macOS has no resolv.conf to edit — the file is generated by the system — so
// DNS is set per network service via networksetup, and every service that was
// changed is recorded so teardown can put each one back.
type darwinConfigurator struct {
	dnsBackup map[string][]string
}

func newNetConfigurator() (netConfigurator, error) {
	return &darwinConfigurator{dnsBackup: map[string][]string{}}, nil
}

func (c *darwinConfigurator) DefaultRoute() (string, string, error) {
	out, err := output("route", "-n", "get", "default")
	if err != nil {
		return "", "", err
	}

	var gateway, iface string
	for _, line := range strings.Split(out, "\n") {
		fields := strings.Fields(line)
		if len(fields) < 2 {
			continue
		}
		switch fields[0] {
		case "gateway:":
			gateway = fields[1]
		case "interface:":
			iface = fields[1]
		}
	}
	if iface == "" {
		return "", "", fmt.Errorf("no default route found")
	}
	return gateway, iface, nil
}

func (c *darwinConfigurator) AddRoute(cidr, gateway, iface string) error {
	// route(8) rejects a duplicate, so replace any existing entry rather than
	// failing a bring-up because of a leftover from a previous crash.
	_ = c.DeleteRoute(cidr, gateway, iface)

	args := []string{"-n", "add", "-net", cidr}
	if gateway != "" {
		args = append(args, gateway)
	} else {
		args = append(args, "-interface", iface)
	}
	return run("route", args...)
}

func (c *darwinConfigurator) DeleteRoute(cidr, gateway, iface string) error {
	if err := run("route", "-n", "delete", "-net", cidr); err != nil {
		// Already absent is the desired end state.
		if strings.Contains(err.Error(), "not in table") {
			return nil
		}
		return err
	}
	return nil
}

func (c *darwinConfigurator) SetDNS(resolver string) error {
	services, err := networkServices()
	if err != nil {
		return err
	}

	for _, service := range services {
		current, err := currentDNS(service)
		if err != nil {
			continue // A service that cannot be read cannot be changed either.
		}
		if err := run("networksetup", "-setdnsservers", service, resolver); err != nil {
			return fmt.Errorf("set DNS on %q: %w", service, err)
		}
		// Recorded only after a successful change, so teardown never tries to
		// restore a service that was left untouched.
		c.dnsBackup[service] = current
	}

	if len(c.dnsBackup) == 0 {
		return fmt.Errorf("no network service accepted a DNS change")
	}
	return nil
}

func (c *darwinConfigurator) RestoreDNS() error {
	var problems []error

	for service, previous := range c.dnsBackup {
		args := []string{"-setdnsservers", service}
		if len(previous) == 0 {
			// networksetup uses the literal "Empty" to mean DHCP-provided.
			args = append(args, "Empty")
		} else {
			args = append(args, previous...)
		}
		if err := run("networksetup", args...); err != nil {
			problems = append(problems, fmt.Errorf("restore DNS on %q: %w", service, err))
		}
	}

	c.dnsBackup = map[string][]string{}
	if len(problems) > 0 {
		return joinErrors(problems)
	}
	return nil
}

// networkServices lists the enabled network services (Wi-Fi, Ethernet, ...).
func networkServices() ([]string, error) {
	out, err := output("networksetup", "-listallnetworkservices")
	if err != nil {
		return nil, fmt.Errorf("list network services: %w", err)
	}

	var services []string
	for i, line := range strings.Split(strings.TrimSpace(out), "\n") {
		// The first line is a header, and a leading asterisk marks a service
		// that is disabled and cannot be configured.
		if i == 0 || strings.HasPrefix(line, "*") || strings.TrimSpace(line) == "" {
			continue
		}
		services = append(services, strings.TrimSpace(line))
	}
	if len(services) == 0 {
		return nil, fmt.Errorf("no enabled network services found")
	}
	return services, nil
}

// currentDNS returns the manually configured resolvers for a service, or an
// empty slice when it is using DHCP.
func currentDNS(service string) ([]string, error) {
	out, err := output("networksetup", "-getdnsservers", service)
	if err != nil {
		return nil, err
	}

	trimmed := strings.TrimSpace(out)
	if strings.Contains(trimmed, "There aren't any DNS Servers set") {
		return nil, nil
	}

	var servers []string
	for _, line := range strings.Split(trimmed, "\n") {
		if s := strings.TrimSpace(line); s != "" {
			servers = append(servers, s)
		}
	}
	return servers, nil
}
