// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * NodeInfo represents a node's published metadata (from Nostr or config).
 */
export class NodeInfo {
    "id": string;
    "nostr_pubkey": string;
    "wg_pubkey": string;
    "endpoint": string;

    /**
     * HTTP base URL for token-gated /connect
     */
    "connect_url"?: string;

    /**
     * Multi-transport capabilities advertised by this node
     */
    "transports"?: TransportCapability[];
    "lnurl": string;
    "deposit_sats": number;
    "upload_mbps": number;
    "download_mbps": number;
    "load": number;
    "capacity": number;
    "role": NodeRole;
    "version": string;

    /**
     * Optional node hint for transport selection
     */
    "preferred_transport"?: Transport;

    /** Creates a new NodeInfo instance. */
    constructor($$source: Partial<NodeInfo> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("nostr_pubkey" in $$source)) {
            this["nostr_pubkey"] = "";
        }
        if (!("wg_pubkey" in $$source)) {
            this["wg_pubkey"] = "";
        }
        if (!("endpoint" in $$source)) {
            this["endpoint"] = "";
        }
        if (!("lnurl" in $$source)) {
            this["lnurl"] = "";
        }
        if (!("deposit_sats" in $$source)) {
            this["deposit_sats"] = 0;
        }
        if (!("upload_mbps" in $$source)) {
            this["upload_mbps"] = 0;
        }
        if (!("download_mbps" in $$source)) {
            this["download_mbps"] = 0;
        }
        if (!("load" in $$source)) {
            this["load"] = 0;
        }
        if (!("capacity" in $$source)) {
            this["capacity"] = 0;
        }
        if (!("role" in $$source)) {
            this["role"] = NodeRole.$zero;
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NodeInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): NodeInfo {
        const $$createField5_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("transports" in $$parsedSource) {
            $$parsedSource["transports"] = $$createField5_0($$parsedSource["transports"]);
        }
        return new NodeInfo($$parsedSource as Partial<NodeInfo>);
    }
}

/**
 * NodeRole defines whether a node serves as entry, exit, or both.
 */
export enum NodeRole {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    RoleEntry = "entry",
    RoleExit = "exit",
    RoleBoth = "both",
};

/**
 * Transport identifies a node data-plane transport.
 */
export enum Transport {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    TransportWireGuard = "wireguard",
    TransportHysteria2 = "hysteria2",
    TransportAmneziaWG = "amneziawg",
};

/**
 * TransportCapability describes one transport a node supports.
 */
export class TransportCapability {
    "transport": Transport;

    /**
     * Data-plane endpoint, e.g. "203.0.113.10:51820"
     */
    "endpoint"?: string;

    /**
     * Control-plane connect API base URL
     */
    "connect_url"?: string;

    /** Creates a new TransportCapability instance. */
    constructor($$source: Partial<TransportCapability> = {}) {
        if (!("transport" in $$source)) {
            this["transport"] = Transport.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TransportCapability instance from a string or object.
     */
    static createFrom($$source: any = {}): TransportCapability {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TransportCapability($$parsedSource as Partial<TransportCapability>);
    }
}

// Private type creation functions
const $$createType0 = TransportCapability.createFrom;
const $$createType1 = $Create.Array($$createType0);
