// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * NodeInfo represents a node's published metadata (from Nostr or config).
 */
export interface NodeInfo {
    "id": string;
    "nostr_pubkey": string;
    "wg_pubkey": string;
    "endpoint": string;

    /**
     * HTTP base URL for token-gated /connect
     */
    "connect_url"?: string;

    /**
     * Multi-transport capabilities advertised by this node
     */
    "transports"?: TransportCapability[] | null;
    "lnurl": string;
    "deposit_sats": number;
    "upload_mbps": number;
    "download_mbps": number;
    "load": number;
    "capacity": number;
    "role": NodeRole;
    "version": string;

    /**
     * Optional node hint for transport selection
     */
    "preferred_transport"?: Transport;
}

/**
 * NodeRole defines whether a node serves as entry, exit, or both.
 */
export enum NodeRole {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    RoleEntry = "entry",
    RoleExit = "exit",
    RoleBoth = "both",
};

/**
 * Transport identifies a node data-plane transport.
 */
export enum Transport {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    TransportWireGuard = "wireguard",
    TransportHysteria2 = "hysteria2",
    TransportAmneziaWG = "amneziawg",
};

/**
 * TransportCapability describes one transport a node supports.
 */
export interface TransportCapability {
    "transport": Transport;

    /**
     * Data-plane endpoint, e.g. "203.0.113.10:51820"
     */
    "endpoint"?: string;

    /**
     * Control-plane connect API base URL
     */
    "connect_url"?: string;
}
