// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {types} from '../models';
import {main} from '../models';

export function AwaitPurchase(arg1:string):Promise<number>;

export function Balance():Promise<number>;

export function ConnectHub(arg1:string):Promise<app.HubStatus>;

export function Disconnect():Promise<void>;

export function ListNodes():Promise<Array<types.NodeInfo>>;

export function Locked():Promise<boolean>;

export function Purchase(arg1:number):Promise<app.Invoice>;

export function Status():Promise<main.StatusView>;

export function Unlock(arg1:string):Promise<main.StatusView>;
