// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {main} from '../models';
import {types} from '../models';

export function AwaitPurchase(arg1:string):Promise<number>;

export function Balance():Promise<number>;

export function ChooseBackupFile():Promise<string>;

export function Connect(arg1:number):Promise<app.Session>;

export function ConnectHub(arg1:string):Promise<app.HubStatus>;

export function CreateKey():Promise<string>;

export function DisableIPv6():Promise<void>;

export function Disconnect():Promise<void>;

export function ExportBackup(arg1:string):Promise<string>;

export function Fingerprint():Promise<string>;

export function HeldSats():Promise<number>;

export function IPv6Exposed():Promise<boolean>;

export function KeyTransfer():Promise<string>;

export function KnownHubs():Promise<Array<main.KnownHub>>;

export function ListNodes():Promise<Array<types.NodeInfo>>;

export function Locked():Promise<boolean>;

export function OpenAtLogin():Promise<boolean>;

export function OpenWallet():Promise<main.StatusView>;

export function PinPair(arg1:string,arg2:string):Promise<void>;

export function PinnedPair():Promise<app.PinnedPair>;

export function PreviewHub(arg1:string):Promise<main.HubPreview>;

export function Purchase(arg1:number):Promise<app.Invoice>;

export function RecommendedHubs():Promise<Array<string>>;

export function ResetVault():Promise<void>;

export function RestoreBackup(arg1:string,arg2:string):Promise<Array<main.RestoredHub>>;

export function Session():Promise<app.Session>;

export function SetOpenAtLogin(arg1:boolean):Promise<void>;

export function Setup():Promise<main.SetupView>;

export function Status():Promise<main.StatusView>;

export function Unlock(arg1:string):Promise<main.StatusView>;

export function UnpinPair():Promise<void>;

export function UpgradeLegacy(arg1:string):Promise<main.StatusView>;

export function Usage():Promise<main.UsageView>;

export function VaultState():Promise<main.VaultStateView>;
