// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AwaitPurchase(arg1) {
  return window['go']['main']['Bridge']['AwaitPurchase'](arg1);
}

export function Balance() {
  return window['go']['main']['Bridge']['Balance']();
}

export function ConnectHub(arg1) {
  return window['go']['main']['Bridge']['ConnectHub'](arg1);
}

export function Disconnect() {
  return window['go']['main']['Bridge']['Disconnect']();
}

export function ListNodes() {
  return window['go']['main']['Bridge']['ListNodes']();
}

export function Locked() {
  return window['go']['main']['Bridge']['Locked']();
}

export function Purchase(arg1) {
  return window['go']['main']['Bridge']['Purchase'](arg1);
}

export function Status() {
  return window['go']['main']['Bridge']['Status']();
}

export function Unlock(arg1) {
  return window['go']['main']['Bridge']['Unlock'](arg1);
}
