// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Bridge exposes the ARFL client to the UI.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as app$0 from "../../internal/app/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../../pkg/types/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AwaitPurchase blocks until the invoice settles, then mints the tokens.
 * 
 * The call is bounded so a never-paid invoice cannot pin a goroutine for the
 * lifetime of the app; the UI reports a timeout and the user can retry.
 */
export function AwaitPurchase(quoteID: string): $CancellablePromise<number> {
    return $Call.ByID(2778801832, quoteID);
}

/**
 * Balance returns unspent sats for the connected hub.
 */
export function Balance(): $CancellablePromise<number> {
    return $Call.ByID(2497382453);
}

/**
 * ChooseBackupFile asks the user for a backup to restore. "" means cancelled.
 */
export function ChooseBackupFile(): $CancellablePromise<string> {
    return $Call.ByID(417033874);
}

/**
 * Connect establishes the two-hop tunnel, paying perHopSats to each node.
 * 
 * The call is bounded: node handshakes and route changes can hang on a
 * misbehaving node, and an unbounded call would leave the UI spinning with no
 * way back to a disconnected state.
 */
export function Connect(perHopSats: number): $CancellablePromise<app$0.Session | null> {
    return $Call.ByID(2465156827, perHopSats);
}

/**
 * ConnectHub points the client at a hub URL the user typed in.
 */
export function ConnectHub(hubURL: string): $CancellablePromise<app$0.HubStatus | null> {
    return $Call.ByID(2237699778, hubURL);
}

/**
 * CreateKey makes the device key and an empty vault sealed by it.
 */
export function CreateKey(): $CancellablePromise<string> {
    return $Call.ByID(1314010598);
}

/**
 * DisableIPv6 turns IPv6 off until the session ends.
 */
export function DisableIPv6(): $CancellablePromise<void> {
    return $Call.ByID(69585596);
}

/**
 * Disconnect tears down the active session.
 */
export function Disconnect(): $CancellablePromise<void> {
    return $Call.ByID(3128456573);
}

/**
 * ExportBackup writes the key and every token to a file the user picks,
 * encrypted with passphrase. It returns the path, or "" if they cancelled.
 */
export function ExportBackup(passphrase: string): $CancellablePromise<string> {
    return $Call.ByID(2749884127, passphrase);
}

/**
 * Fingerprint returns the device key's fingerprint, or "" before one exists.
 */
export function Fingerprint(): $CancellablePromise<string> {
    return $Call.ByID(2136477249);
}

/**
 * HeldSats is the value of every token on this device, across all hubs. It is
 * what a lost device without a backup would take with it.
 */
export function HeldSats(): $CancellablePromise<number> {
    return $Call.ByID(1883277757);
}

/**
 * IPv6Exposed reports whether this machine has IPv6 the tunnel does not cover.
 */
export function IPv6Exposed(): $CancellablePromise<boolean> {
    return $Call.ByID(751340222);
}

/**
 * KeyTransfer returns the device key in the form the "Move to a new device"
 * QR carries. Tokens are deliberately not included; they travel only in the
 * encrypted backup file.
 */
export function KeyTransfer(): $CancellablePromise<string> {
    return $Call.ByID(1155308933);
}

/**
 * KnownHubs lists the recommended hubs plus every hub this wallet holds
 * tokens at, each with its public info and the local balance there.
 */
export function KnownHubs(): $CancellablePromise<$models.KnownHub[] | null> {
    return $Call.ByID(71136906);
}

/**
 * ListNodes returns the hub's online nodes.
 */
export function ListNodes(): $CancellablePromise<types$0.NodeInfo[] | null> {
    return $Call.ByID(314861188);
}

/**
 * Locked reports whether the vault still needs a passphrase.
 */
export function Locked(): $CancellablePromise<boolean> {
    return $Call.ByID(3321945505);
}

/**
 * OpenAtLogin reports whether ARFL starts when the user signs in. Wails
 * registers a login item through SMAppService on macOS, the Run key on
 * Windows and an XDG autostart entry on Linux.
 */
export function OpenAtLogin(): $CancellablePromise<boolean> {
    return $Call.ByID(886631707);
}

/**
 * OpenWallet opens the vault with the device key on every launch after the
 * first, so the user is never asked for a password.
 */
export function OpenWallet(): $CancellablePromise<$models.StatusView | null> {
    return $Call.ByID(1715399630);
}

/**
 * PinPair makes later connects use the chosen entry and exit nodes.
 */
export function PinPair(entryID: string, exitID: string): $CancellablePromise<void> {
    return $Call.ByID(2742549550, entryID, exitID);
}

/**
 * PinnedPair returns the user's chosen pair, or nil when pairing is random.
 */
export function PinnedPair(): $CancellablePromise<app$0.PinnedPair | null> {
    return $Call.ByID(3062685517);
}

/**
 * PreviewHub reads a hub's public info without connecting to it.
 */
export function PreviewHub(hubURL: string): $CancellablePromise<$models.HubPreview | null> {
    return $Call.ByID(2208574280, hubURL);
}

/**
 * Purchase requests a Lightning invoice for bandwidth credit.
 */
export function Purchase(amountSats: number): $CancellablePromise<app$0.Invoice | null> {
    return $Call.ByID(4002128072, amountSats);
}

/**
 * RecommendedHubs lists the hubs the chooser offers before the user adds one.
 */
export function RecommendedHubs(): $CancellablePromise<string[] | null> {
    return $Call.ByID(3179063902);
}

/**
 * ResetVault deletes the local encrypted token vault.
 * 
 * This is only allowed while locked. Deleting while unlocked would orphan the
 * in-memory service state from the file on disk.
 */
export function ResetVault(): $CancellablePromise<void> {
    return $Call.ByID(2464251658);
}

/**
 * RestoreBackup brings a backed-up key and its tokens to this device. Each
 * hub is asked which tokens are still unspent, and spent ones are dropped.
 */
export function RestoreBackup(path: string, passphrase: string): $CancellablePromise<$models.RestoredHub[] | null> {
    return $Call.ByID(431276389, path, passphrase);
}

/**
 * Session returns the active session, or nil when disconnected.
 */
export function Session(): $CancellablePromise<app$0.Session | null> {
    return $Call.ByID(4044722465);
}

/**
 * SetOpenAtLogin adds or removes ARFL from the user's login items.
 */
export function SetOpenAtLogin(on: boolean): $CancellablePromise<void> {
    return $Call.ByID(113509713, on);
}

/**
 * Setup reports whether this device already has a key.
 */
export function Setup(): $CancellablePromise<$models.SetupView | null> {
    return $Call.ByID(3227868360);
}

/**
 * ShowMain brings the main window forward and, when overlay is set, opens
 * that drawer in it.
 */
export function ShowMain(overlay: string): $CancellablePromise<void> {
    return $Call.ByID(3576056131, overlay);
}

/**
 * Status returns the current snapshot for the UI.
 */
export function Status(): $CancellablePromise<$models.StatusView | null> {
    return $Call.ByID(940942817);
}

/**
 * Unlock opens the encrypted proof vault. Calling it again is a no-op, since
 * re-opening the store while a session is live would drop that session.
 */
export function Unlock(passphrase: string): $CancellablePromise<$models.StatusView | null> {
    return $Call.ByID(3850666575, passphrase);
}

/**
 * UnpinPair goes back to a random pair chosen at connect time.
 */
export function UnpinPair(): $CancellablePromise<void> {
    return $Call.ByID(2270732215);
}

/**
 * UpgradeLegacy moves a passphrase wallet onto a new device key. The old file
 * is kept beside the new one until the move has fully succeeded.
 */
export function UpgradeLegacy(passphrase: string): $CancellablePromise<$models.StatusView | null> {
    return $Call.ByID(3758703246, passphrase);
}

/**
 * Usage reports bytes carried by the tunnel this session.
 */
export function Usage(): $CancellablePromise<$models.UsageView | null> {
    return $Call.ByID(3219775478);
}

/**
 * VaultState reports whether the local encrypted vault file exists.
 */
export function VaultState(): $CancellablePromise<$models.VaultStateView | null> {
    return $Call.ByID(2744106450);
}
