// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * HubPreview is what the hub chooser shows before the user commits to a hub.
 */
export class HubPreview {
    "url": string;
    "name": string;
    "margin_pct": number;
    "node_count": number;

    /** Creates a new HubPreview instance. */
    constructor($$source: Partial<HubPreview> = {}) {
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("margin_pct" in $$source)) {
            this["margin_pct"] = 0;
        }
        if (!("node_count" in $$source)) {
            this["node_count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HubPreview instance from a string or object.
     */
    static createFrom($$source: any = {}): HubPreview {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HubPreview($$parsedSource as Partial<HubPreview>);
    }
}

/**
 * KnownHub is a hub the user can switch to, with what they hold there.
 */
export class KnownHub {
    "url": string;
    "name": string;
    "margin_pct": number;
    "node_count": number;
    "sats": number;
    "reachable": boolean;
    "custom": boolean;

    /** Creates a new KnownHub instance. */
    constructor($$source: Partial<KnownHub> = {}) {
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("margin_pct" in $$source)) {
            this["margin_pct"] = 0;
        }
        if (!("node_count" in $$source)) {
            this["node_count"] = 0;
        }
        if (!("sats" in $$source)) {
            this["sats"] = 0;
        }
        if (!("reachable" in $$source)) {
            this["reachable"] = false;
        }
        if (!("custom" in $$source)) {
            this["custom"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KnownHub instance from a string or object.
     */
    static createFrom($$source: any = {}): KnownHub {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new KnownHub($$parsedSource as Partial<KnownHub>);
    }
}

/**
 * RestoredHub is one hub's balance after a backup is restored.
 */
export class RestoredHub {
    "hub_url": string;
    "name": string;
    "sats": number;
    "dropped_sats": number;
    "error"?: string;

    /** Creates a new RestoredHub instance. */
    constructor($$source: Partial<RestoredHub> = {}) {
        if (!("hub_url" in $$source)) {
            this["hub_url"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("sats" in $$source)) {
            this["sats"] = 0;
        }
        if (!("dropped_sats" in $$source)) {
            this["dropped_sats"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RestoredHub instance from a string or object.
     */
    static createFrom($$source: any = {}): RestoredHub {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RestoredHub($$parsedSource as Partial<RestoredHub>);
    }
}

/**
 * SetupView tells the UI which first-launch path to show.
 */
export class SetupView {
    "has_key": boolean;
    "fingerprint"?: string;

    /**
     * LegacyVault is a wallet from before device keys, still sealed by a
     * passphrase. It must be unlocked once to move it onto a device key.
     */
    "legacy_vault": boolean;

    /** Creates a new SetupView instance. */
    constructor($$source: Partial<SetupView> = {}) {
        if (!("has_key" in $$source)) {
            this["has_key"] = false;
        }
        if (!("legacy_vault" in $$source)) {
            this["legacy_vault"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SetupView instance from a string or object.
     */
    static createFrom($$source: any = {}): SetupView {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SetupView($$parsedSource as Partial<SetupView>);
    }
}

/**
 * StatusView is the snapshot the UI renders on every state change.
 */
export class StatusView {
    "unlocked": boolean;
    "hub_url": string;
    "state": string;
    "balance_sats": number;

    /**
     * TunnelReady reports whether privileged networking is available. The UI
     * disables Connect when it is not, rather than letting the user pay for a
     * session that cannot be established.
     */
    "tunnel_ready": boolean;

    /**
     * TunnelError explains an unavailable tunnel, typically missing root.
     */
    "tunnel_error"?: string;

    /**
     * Error carries a non-fatal problem (for example an unreadable balance)
     * without failing the whole call, so the UI can still render.
     */
    "error"?: string;

    /** Creates a new StatusView instance. */
    constructor($$source: Partial<StatusView> = {}) {
        if (!("unlocked" in $$source)) {
            this["unlocked"] = false;
        }
        if (!("hub_url" in $$source)) {
            this["hub_url"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("balance_sats" in $$source)) {
            this["balance_sats"] = 0;
        }
        if (!("tunnel_ready" in $$source)) {
            this["tunnel_ready"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StatusView instance from a string or object.
     */
    static createFrom($$source: any = {}): StatusView {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StatusView($$parsedSource as Partial<StatusView>);
    }
}

/**
 * UsageView is live traffic through the tunnel.
 */
export class UsageView {
    "connected": boolean;
    "rx_bytes": number;
    "tx_bytes": number;

    /**
     * Seconds since the last handshake with each node; -1 before the first.
     */
    "entry_idle_secs": number;
    "exit_idle_secs": number;

    /** Creates a new UsageView instance. */
    constructor($$source: Partial<UsageView> = {}) {
        if (!("connected" in $$source)) {
            this["connected"] = false;
        }
        if (!("rx_bytes" in $$source)) {
            this["rx_bytes"] = 0;
        }
        if (!("tx_bytes" in $$source)) {
            this["tx_bytes"] = 0;
        }
        if (!("entry_idle_secs" in $$source)) {
            this["entry_idle_secs"] = 0;
        }
        if (!("exit_idle_secs" in $$source)) {
            this["exit_idle_secs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UsageView instance from a string or object.
     */
    static createFrom($$source: any = {}): UsageView {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UsageView($$parsedSource as Partial<UsageView>);
    }
}

/**
 * VaultStateView describes whether a local encrypted token vault already
 * exists. The UI uses this to switch between first-run "create" and
 * returning-user "unlock" flows.
 */
export class VaultStateView {
    "exists": boolean;

    /** Creates a new VaultStateView instance. */
    constructor($$source: Partial<VaultStateView> = {}) {
        if (!("exists" in $$source)) {
            this["exists"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VaultStateView instance from a string or object.
     */
    static createFrom($$source: any = {}): VaultStateView {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VaultStateView($$parsedSource as Partial<VaultStateView>);
    }
}
