// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * HubPreview is what the hub chooser shows before the user commits to a hub.
 */
export interface HubPreview {
    "url": string;
    "name": string;
    "margin_pct": number;
    "node_count": number;

    /**
     * Trusted is true for hubs on the ARFL trusted list.
     */
    "trusted": boolean;
}

/**
 * KnownHub is a hub the user can switch to, with what they hold there.
 */
export interface KnownHub {
    "url": string;
    "name": string;
    "margin_pct": number;
    "node_count": number;

    /**
     * Trusted is true for hubs on the ARFL trusted list.
     */
    "trusted": boolean;
    "sats": number;
    "reachable": boolean;
    "custom": boolean;
}

/**
 * RestoredHub is one hub's balance after a backup is restored.
 */
export interface RestoredHub {
    "hub_url": string;
    "name": string;
    "sats": number;
    "dropped_sats": number;
    "error"?: string;
}

/**
 * SetupView tells the UI which first-launch path to show.
 */
export interface SetupView {
    "has_key": boolean;
    "fingerprint"?: string;

    /**
     * LegacyVault is a wallet from before device keys, still sealed by a
     * passphrase. It must be unlocked once to move it onto a device key.
     */
    "legacy_vault": boolean;
}

/**
 * StatusView is the snapshot the UI renders on every state change.
 */
export interface StatusView {
    "unlocked": boolean;
    "hub_url": string;
    "state": string;
    "balance_sats": number;

    /**
     * TunnelReady reports whether privileged networking is available. The UI
     * disables Connect when it is not, rather than letting the user pay for a
     * session that cannot be established.
     */
    "tunnel_ready": boolean;

    /**
     * TunnelError explains an unavailable tunnel, typically missing root.
     */
    "tunnel_error"?: string;

    /**
     * HelperSetup is true when "Set up the tunnel" would enable Connect.
     */
    "helper_setup": boolean;

    /**
     * Error carries a non-fatal problem (for example an unreadable balance)
     * without failing the whole call, so the UI can still render.
     */
    "error"?: string;
}

/**
 * UsageView is live traffic through the tunnel.
 */
export interface UsageView {
    "connected": boolean;
    "rx_bytes": number;
    "tx_bytes": number;

    /**
     * Seconds since the last handshake with each node; -1 before the first.
     */
    "entry_idle_secs": number;
    "exit_idle_secs": number;
}

/**
 * VaultStateView describes whether a local encrypted token vault already
 * exists. The UI uses this to switch between first-run "create" and
 * returning-user "unlock" flows.
 */
export interface VaultStateView {
    "exists": boolean;
}
