package types

import "time"

// NodeRole defines whether a node serves as entry, exit, or both.
type NodeRole string

const (
	RoleEntry NodeRole = "entry"
	RoleExit  NodeRole = "exit"
	RoleBoth  NodeRole = "both"
)

// Transport identifies a node data-plane transport.
type Transport string

const (
	TransportWireGuard Transport = "wireguard"
	TransportHysteria2 Transport = "hysteria2"
	TransportAmneziaWG Transport = "amneziawg"
)

// TransportCapability describes one transport a node supports.
type TransportCapability struct {
	Transport  Transport `json:"transport"`
	Endpoint   string    `json:"endpoint,omitempty"`    // Data-plane endpoint, e.g. "203.0.113.10:51820"
	ConnectURL string    `json:"connect_url,omitempty"` // Control-plane connect API base URL
}

// NodeInfo represents a node's published metadata (from Nostr or config).
type NodeInfo struct {
	ID                 string                `json:"id"`
	NostrPubkey        string                `json:"nostr_pubkey"`
	WGPubkey           string                `json:"wg_pubkey"`
	Endpoint           string                `json:"endpoint"`
	ConnectURL         string                `json:"connect_url,omitempty"` // HTTP base URL for token-gated /connect
	Transports         []TransportCapability `json:"transports,omitempty"`  // Multi-transport capabilities advertised by this node
	LNURL              string                `json:"lnurl"`
	DepositSats        int64                 `json:"deposit_sats"`
	UploadMbps         int                   `json:"upload_mbps"`
	DownloadMbps       int                   `json:"download_mbps"`
	Load               int                   `json:"load"`
	Capacity           int                   `json:"capacity"`
	Role               NodeRole              `json:"role"`
	Version            string                `json:"version"`
	PreferredTransport Transport             `json:"preferred_transport,omitempty"` // Optional node hint for transport selection
}

// SessionConfig holds the parameters for a two-hop session.
// In Phase 1 this is loaded from a static JSON file.
// In Phase 2+ it is generated by the hub/control plane.
type SessionConfig struct {
	SessionID   string   `json:"session_id"`
	EntryNode   NodeInfo `json:"entry_node"`
	ExitNode    NodeInfo `json:"exit_node"`
	ClientWGPub string   `json:"client_wg_pubkey"`
	Transport   string   `json:"transport,omitempty"` // Selected session transport (e.g. "wireguard", "hysteria2")
	OuterTunIP  string   `json:"outer_tunnel_ip"`     // e.g. 10.100.0.2
	InnerTunIP  string   `json:"inner_tunnel_ip"`     // e.g. 10.200.0.2
	QuotaMB     int64    `json:"quota_mb"`
}

// PeerStats holds byte counter data for a WireGuard peer.
type PeerStats struct {
	PublicKey     string    `json:"public_key"`
	ReceiveBytes  int64     `json:"receive_bytes"`
	TransmitBytes int64     `json:"transmit_bytes"`
	TotalBytes    int64     `json:"total_bytes"`
	LastHandshake time.Time `json:"last_handshake"`
}

// BandwidthCredential is the abstraction for bandwidth tokens.
// Phase 4: signed directly by hub. Phase 5: blind-signed (Chaumian ecash).
type BandwidthCredential struct {
	ValueGB      int    `json:"value_gb"`
	IssuerPubkey []byte `json:"issuer_pubkey"`
	Expiry       int64  `json:"expiry"`
	Nullifier    []byte `json:"nullifier"`
	Signature    []byte `json:"signature"`
}

// WebhookEvent represents a protocol event pushed to subscribed hubs.
type WebhookEvent struct {
	Type      string `json:"type"`
	Timestamp int64  `json:"timestamp"`
	NodeID    string `json:"node_id,omitempty"`
	SessionID string `json:"session_id,omitempty"`
	Data      any    `json:"data,omitempty"`
}

// Webhook event type constants.
const (
	EventNodeOffline     = "NODE_OFFLINE"
	EventNodeOnline      = "NODE_ONLINE"
	EventRefundTriggered = "REFUND_TRIGGERED"
	EventDepositLow      = "DEPOSIT_LOW"
	EventDepositDepleted = "DEPOSIT_DEPLETED"
	EventGBBalanceLow    = "GB_BALANCE_LOW"
	EventSessionStarted  = "SESSION_STARTED"
	EventSessionEnded    = "SESSION_ENDED"
	EventSettlementSent  = "SETTLEMENT_SENT"
)
