// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../../pkg/types/models.js";

/**
 * HopConfig describes one leg of the two-hop tunnel.
 */
export interface HopConfig {
    "node_id": string;
    "endpoint": string;
    "node_wg_pubkey": string;
    "tunnel_ip": string;
    "bytes_allowed": number;
}

/**
 * HubStatus summarises a connected hub for display.
 */
export interface HubStatus {
    "url": string;
    "name": string;
    "version": string;
    "keyset_id": string;
    "balance_sats": number;
    "node_count": number;
}

/**
 * Invoice is a pending bandwidth purchase awaiting Lightning payment.
 */
export interface Invoice {
    "quote_id": string;
    "bolt11": string;

    /**
     * PaymentHash lets the user reconcile the payment against their Lightning
     * wallet without having to decode the BOLT11 themselves.
     */
    "payment_hash": string;
    "amount_sats": number;
    "expires_at": string;
}

/**
 * PinnedPair names the entry and exit nodes a user chose by ID.
 */
export interface PinnedPair {
    "entry_id": string;
    "exit_id": string;
}

/**
 * Session describes an active two-hop connection.
 */
export interface Session {
    "state": State;
    "config": TunnelConfig;
    "spent_sats": number;
    "started_at": string;
}

/**
 * State is the connection state machine exposed to the UI.
 */
export enum State {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StateDisconnected = "disconnected",
    StateConnecting = "connecting",
    StateConnected = "connected",
    StateDisconnecting = "disconnecting",
};

/**
 * TunnelConfig is everything a Tunnel needs to establish both hops.
 */
export interface TunnelConfig {
    "entry": HopConfig;
    "exit": HopConfig;
    "client_key": string;
    "entry_client_key"?: string;
    "exit_client_key"?: string;

    /**
     * OuterPinnedEndpoints are additional host:port endpoints that must be
     * pinned through the outer tunnel during staged setup.
     * 
     * This keeps HTTP provisioning endpoints and the real exit WireGuard
     * endpoint both routed through the entry hop when they differ by host.
     */
    "outer_pinned_endpoints"?: string[] | null;
    "transport"?: types$0.Transport;
}
